create table employee (
    id  int generated by default as identity,
    lastName       varchar(100)    not null,
    firstName  varchar(100)    not null,
    email   varchar(100)    not null,
    primary key (id)
);