insert into person (full_name, gender, job, city, salary) values ('Tomkin Rawe', 'Non-binary', 'Account Coordinator', 'General Lavalle', 1877.14);
insert into person (full_name, gender, job, city, salary) values ('Garey Dobbing', 'Polygender', 'Payment Adjustment Coordinator', 'Silago', 8326.10);
insert into person (full_name, gender, job, city, salary) values ('Ariela Dandison', 'Genderqueer', 'Analyst Programmer', 'Araçatuba', 879.57);
insert into person (full_name, gender, job, city, salary) values ('Rebekah Benoist', 'Non-binary', 'Senior Developer', 'Hexia', 4099.35);
insert into person (full_name, gender, job, city, salary) values ('Willette Ayrton', 'Male', 'Environmental Tech', 'Khudāydād Khēl', 6489.15);
insert into person (full_name, gender, job, city, salary) values ('Maurizio Mitchall', 'Female', 'Associate Professor', 'Yidu', 1762.37);
insert into person (full_name, gender, job, city, salary) values ('Waylon Parvin', 'Polygender', 'Research Associate', 'Banatsko Karađorđevo', 4158.56);
insert into person (full_name, gender, job, city, salary) values ('Marie Kleinholz', 'Genderfluid', 'Safety Technician III', 'Borzytuchom', 3658.61);
insert into person (full_name, gender, job, city, salary) values ('Harbert Jersch', 'Bigender', 'Recruiting Manager', 'Sempu', 6708.95);
insert into person (full_name, gender, job, city, salary) values ('Justis Wandrey', 'Male', 'Sales Representative', 'Chýnov', 2917.68);
insert into person (full_name, gender, job, city, salary) values ('Dorian Sitlington', 'Genderfluid', 'Senior Sales Associate', 'Nanjie', 5155.35);
insert into person (full_name, gender, job, city, salary) values ('Violante Cheatle', 'Non-binary', 'Product Engineer', 'Zhize', 2643.59);
insert into person (full_name, gender, job, city, salary) values ('Rance Joao', 'Male', 'Food Chemist', 'Hoeryŏng', 4378.50);
insert into person (full_name, gender, job, city, salary) values ('Jarred Pinnegar', 'Male', 'Structural Analysis Engineer', 'Kansas City', 7016.78);
insert into person (full_name, gender, job, city, salary) values ('Horton Kierans', 'Polygender', 'Human Resources Assistant III', 'Portariá', 4841.86);
insert into person (full_name, gender, job, city, salary) values ('Niccolo Frostdyke', 'Bigender', 'VP Sales', 'Xiaodukou', 3346.60);
insert into person (full_name, gender, job, city, salary) values ('Misty Ashford', 'Genderqueer', 'Physical Therapy Assistant', 'Kalāt-e Nāderī', 9200.57);
insert into person (full_name, gender, job, city, salary) values ('Osbert Fassbindler', 'Male', 'Staff Accountant II', 'Karanlukh', 9583.33);
insert into person (full_name, gender, job, city, salary) values ('Hersh Norley', 'Genderfluid', 'Statistician I', 'David', 9091.61);
insert into person (full_name, gender, job, city, salary) values ('Hayward Gameson', 'Female', 'VP Marketing', 'Doudleby nad Orlicí', 3552.99);
insert into person (full_name, gender, job, city, salary) values ('Verney Belitz', 'Bigender', 'Occupational Therapist', 'Vista Hermosa', 2719.43);
insert into person (full_name, gender, job, city, salary) values ('Barry Dibble', 'Female', 'Information Systems Manager', 'Tapel', 8172.22);
insert into person (full_name, gender, job, city, salary) values ('Giselbert Medlicott', 'Male', 'Staff Scientist', 'Juatuba', 7656.21);
insert into person (full_name, gender, job, city, salary) values ('Malachi Temlett', 'Bigender', 'Community Outreach Specialist', 'Bāglung', 8943.75);
insert into person (full_name, gender, job, city, salary) values ('Colver Redfield', 'Polygender', 'Pharmacist', 'Chetian', 1759.10);
insert into person (full_name, gender, job, city, salary) values ('Averill Lakey', 'Male', 'Senior Sales Associate', 'Moscow', 8930.47);
insert into person (full_name, gender, job, city, salary) values ('Lyell Hanlin', 'Polygender', 'Tax Accountant', 'San Bernardo', 7705.35);
insert into person (full_name, gender, job, city, salary) values ('Berrie Reggio', 'Polygender', 'Web Developer III', 'Shāhdādkot', 8910.34);
insert into person (full_name, gender, job, city, salary) values ('Flo Ezzle', 'Male', 'Teacher', 'Dushanbe', 4879.23);
insert into person (full_name, gender, job, city, salary) values ('Tomasina Couroy', 'Bigender', 'Biostatistician II', 'Barlinek', 5526.16);
insert into person (full_name, gender, job, city, salary) values ('Eric Durrington', 'Non-binary', 'Executive Secretary', 'Eyvān', 9582.39);
insert into person (full_name, gender, job, city, salary) values ('Dasi Romero', 'Bigender', 'Pharmacist', 'Ban Rangsit', 9224.40);
insert into person (full_name, gender, job, city, salary) values ('Nadya Spurgin', 'Female', 'Biostatistician I', 'Gaofeng', 8214.64);
insert into person (full_name, gender, job, city, salary) values ('Stefano Pehrsson', 'Polygender', 'Senior Sales Associate', 'Dongping', 9368.18);
insert into person (full_name, gender, job, city, salary) values ('Mella Clee', 'Female', 'Electrical Engineer', 'Yamoto', 8389.76);
insert into person (full_name, gender, job, city, salary) values ('Dyanne Grimsdell', 'Genderfluid', 'Engineer IV', 'Mūḩ Ḩasan', 9885.07);
insert into person (full_name, gender, job, city, salary) values ('Arie Sivior', 'Genderfluid', 'Software Engineer I', 'Haparanda', 9331.89);
insert into person (full_name, gender, job, city, salary) values ('Hillard Maggiori', 'Polygender', 'Assistant Manager', 'La Calera', 5258.51);
insert into person (full_name, gender, job, city, salary) values ('Merilyn Baythrop', 'Bigender', 'Media Manager III', 'Duas Igrejas', 9285.27);
insert into person (full_name, gender, job, city, salary) values ('Roxie Clines', 'Genderqueer', 'Recruiting Manager', 'Casuguran', 4588.58);
insert into person (full_name, gender, job, city, salary) values ('Mara Raith', 'Bigender', 'Software Engineer III', 'Catarman', 6863.75);
insert into person (full_name, gender, job, city, salary) values ('Terencio Dusting', 'Male', 'Media Manager II', 'Tulay', 1961.92);
insert into person (full_name, gender, job, city, salary) values ('Nathalie Dennerley', 'Agender', 'Accounting Assistant II', 'Bajawa', 3813.97);
insert into person (full_name, gender, job, city, salary) values ('Ricky Dearn', 'Genderfluid', 'Safety Technician I', 'Debark’', 8366.00);
insert into person (full_name, gender, job, city, salary) values ('Van Lydden', 'Genderfluid', 'Assistant Media Planner', 'Sosnovka', 3968.38);
insert into person (full_name, gender, job, city, salary) values ('Matthieu Chalcroft', 'Female', 'General Manager', 'Wattegama', 4652.07);
insert into person (full_name, gender, job, city, salary) values ('Iggy Heath', 'Genderfluid', 'Financial Analyst', 'Oslo', 6318.99);
insert into person (full_name, gender, job, city, salary) values ('Tandie Iacopo', 'Bigender', 'Budget/Accounting Analyst III', 'Mikhaylovsk', 744.17);
insert into person (full_name, gender, job, city, salary) values ('Skye O''Mullaney', 'Non-binary', 'General Manager', 'Raciąż', 8296.39);
insert into person (full_name, gender, job, city, salary) values ('Swen Chooter', 'Genderqueer', 'Information Systems Manager', 'Mugi', 8053.42);
