insert into customer (first_name, last_name, email, phone, job) values ('Birk', 'Goodwyn', 'bgoodwyn0@sciencedaily.com', '525-710-0103', 'Software Consultant');
insert into customer (first_name, last_name, email, phone, job) values ('Carie', 'Eckery', 'ceckery1@360.cn', '433-753-6309', 'Senior Sales Associate');
insert into customer (first_name, last_name, email, phone, job) values ('Dena', 'Featherbie', 'dfeatherbie2@vistaprint.com', '838-740-9736', 'Editor');
insert into customer (first_name, last_name, email, phone, job) values ('Edin', 'Taylour', 'etaylour3@github.io', '749-574-6870', 'Nuclear Power Engineer');
insert into customer (first_name, last_name, email, phone, job) values ('Xever', 'Stennes', 'xstennes4@umich.edu', '983-616-2937', 'Sales Associate');
insert into customer (first_name, last_name, email, phone, job) values ('Christos', 'Cleynaert', 'ccleynaert5@vk.com', '872-850-7797', 'Librarian');
insert into customer (first_name, last_name, email, phone, job) values ('Lanny', 'Minshall', 'lminshall6@utexas.edu', '146-897-0947', 'Cost Accountant');
insert into customer (first_name, last_name, email, phone, job) values ('Warde', 'Dellenbrook', 'wdellenbrook7@etsy.com', '296-539-9500', 'Recruiting Manager');
insert into customer (first_name, last_name, email, phone, job) values ('Elysha', 'Grouer', 'egrouer8@ameblo.jp', '641-574-8415', 'Structural Engineer');
insert into customer (first_name, last_name, email, phone, job) values ('Cari', 'Jalland', 'cjalland9@cdc.gov', '266-644-6945', 'Marketing Manager');
insert into customer (first_name, last_name, email, phone, job) values ('Sybille', 'Pyffe', 'spyffea@ifeng.com', '120-910-8110', 'Engineer IV');
insert into customer (first_name, last_name, email, phone, job) values ('Hayden', 'Giocannoni', 'hgiocannonib@auda.org.au', '147-916-4434', 'Chemical Engineer');
insert into customer (first_name, last_name, email, phone, job) values ('Sherman', 'Grubey', 'sgrubeyc@howstuffworks.com', '227-796-1624', 'Community Outreach Specialist');
insert into customer (first_name, last_name, email, phone, job) values ('Kelley', 'Radbourne', 'kradbourned@twitpic.com', '417-522-1799', 'Accountant IV');
insert into customer (first_name, last_name, email, phone, job) values ('Maximilien', 'Matthewson', 'mmatthewsone@posterous.com', '764-125-6966', 'Product Engineer');
insert into customer (first_name, last_name, email, phone, job) values ('Jarib', 'Grimsell', 'jgrimsellf@cam.ac.uk', '968-134-5533', 'Environmental Tech');
insert into customer (first_name, last_name, email, phone, job) values ('Brnaba', 'Mothersole', 'bmothersoleg@unblog.fr', '389-851-9054', 'Database Administrator I');
insert into customer (first_name, last_name, email, phone, job) values ('Thaddus', 'Neill', 'tneillh@tmall.com', '422-389-8196', 'Quality Engineer');
insert into customer (first_name, last_name, email, phone, job) values ('Stefano', 'Arkle', 'sarklei@pagesperso-orange.fr', '350-499-2033', 'Social Worker');
insert into customer (first_name, last_name, email, phone, job) values ('Ciro', 'Chong', 'cchongj@redcross.org', '139-936-5488', 'Executive Secretary');
insert into customer (first_name, last_name, email, phone, job) values ('Rustin', 'Pigram', 'rpigramk@so-net.ne.jp', '508-506-2634', 'Project Manager');
insert into customer (first_name, last_name, email, phone, job) values ('Anstice', 'Balentyne', 'abalentynel@sciencedirect.com', '148-562-4262', 'Senior Developer');
insert into customer (first_name, last_name, email, phone, job) values ('Hyman', 'Battlestone', 'hbattlestonem@wired.com', '105-279-1118', 'Software Test Engineer III');
insert into customer (first_name, last_name, email, phone, job) values ('Maryellen', 'Denisevich', 'mdenisevichn@slate.com', '284-602-1117', 'Design Engineer');
insert into customer (first_name, last_name, email, phone, job) values ('Patrick', 'Kyd', 'pkydo@netlog.com', '426-198-6217', 'Account Executive');
insert into customer (first_name, last_name, email, phone, job) values ('Joelie', 'Teek', 'jteekp@tumblr.com', '922-510-0423', 'Analyst Programmer');
insert into customer (first_name, last_name, email, phone, job) values ('Rosette', 'Gunstone', 'rgunstoneq@yahoo.com', '314-631-1029', 'Associate Professor');
insert into customer (first_name, last_name, email, phone, job) values ('Madel', 'Karlolczak', 'mkarlolczakr@ucla.edu', '430-936-1595', 'Programmer Analyst III');
insert into customer (first_name, last_name, email, phone, job) values ('Misti', 'Jerman', 'mjermans@nationalgeographic.com', '730-317-7484', 'Assistant Media Planner');
insert into customer (first_name, last_name, email, phone, job) values ('Ignatius', 'Grafhom', 'igrafhomt@blogspot.com', '651-384-2002', 'VP Product Management');
insert into customer (first_name, last_name, email, phone, job) values ('Lauritz', 'LLelweln', 'lllelwelnu@amazon.de', '356-726-9243', 'Nuclear Power Engineer');
insert into customer (first_name, last_name, email, phone, job) values ('Anna-diana', 'Rickesies', 'arickesiesv@chronoengine.com', '310-711-7429', 'Web Designer IV');
insert into customer (first_name, last_name, email, phone, job) values ('Loise', 'Justis', 'ljustisw@blogs.com', '955-167-5072', 'Budget/Accounting Analyst III');
insert into customer (first_name, last_name, email, phone, job) values ('Raynell', 'Bolley', 'rbolleyx@deliciousdays.com', '105-315-7380', 'Senior Developer');
insert into customer (first_name, last_name, email, phone, job) values ('Cori', 'Luce', 'clucey@upenn.edu', '610-975-6031', 'Actuary');
insert into customer (first_name, last_name, email, phone, job) values ('Jennifer', 'Stadden', 'jstaddenz@stanford.edu', '840-475-0350', 'Design Engineer');
insert into customer (first_name, last_name, email, phone, job) values ('Mari', 'Hubbins', 'mhubbins10@indiegogo.com', '369-129-2277', 'Junior Executive');
insert into customer (first_name, last_name, email, phone, job) values ('Glory', 'Torritti', 'gtorritti11@bloglovin.com', '825-487-2846', 'Director of Sales');
insert into customer (first_name, last_name, email, phone, job) values ('Abelard', 'Nesbitt', 'anesbitt12@issuu.com', '919-950-6819', 'Product Engineer');
insert into customer (first_name, last_name, email, phone, job) values ('Faith', 'Vidyapin', 'fvidyapin13@earthlink.net', '814-456-3348', 'Assistant Manager');
insert into customer (first_name, last_name, email, phone, job) values ('Syd', 'Stachini', 'sstachini14@bandcamp.com', '562-992-4233', 'Internal Auditor');
insert into customer (first_name, last_name, email, phone, job) values ('Cymbre', 'Nafziger', 'cnafziger15@netscape.com', '199-637-1770', 'Quality Engineer');
insert into customer (first_name, last_name, email, phone, job) values ('Godfry', 'Piscotti', 'gpiscotti16@elpais.com', '482-835-1547', 'Staff Scientist');
insert into customer (first_name, last_name, email, phone, job) values ('Liv', 'Bunton', 'lbunton17@ebay.co.uk', '963-626-8490', 'Administrative Assistant IV');
insert into customer (first_name, last_name, email, phone, job) values ('Anne', 'Ben', 'aben18@last.fm', '710-802-6802', 'Assistant Professor');
insert into customer (first_name, last_name, email, phone, job) values ('Hilarius', 'Boylin', 'hboylin19@tinypic.com', '406-919-5428', 'Environmental Specialist');
insert into customer (first_name, last_name, email, phone, job) values ('Gil', 'Sconce', 'gsconce1a@webs.com', '583-537-6172', 'Geological Engineer');
insert into customer (first_name, last_name, email, phone, job) values ('Desi', 'Blakiston', 'dblakiston1b@dot.gov', '404-343-5637', 'Staff Accountant I');
insert into customer (first_name, last_name, email, phone, job) values ('Wynnie', 'Lease', 'wlease1c@tripod.com', '922-362-6029', 'Structural Engineer');
insert into customer (first_name, last_name, email, phone, job) values ('Rolph', 'Walcher', 'rwalcher1d@mozilla.com', '825-382-1994', 'Graphic Designer');
insert into customer (first_name, last_name, email, phone, job) values ('Olympe', 'Vernon', 'overnon1e@instagram.com', '714-751-1988', 'Software Engineer III');
insert into customer (first_name, last_name, email, phone, job) values ('Evyn', 'Jamieson', 'ejamieson1f@paginegialle.it', '735-215-9866', 'Structural Engineer');
insert into customer (first_name, last_name, email, phone, job) values ('Roselia', 'Goodoune', 'rgoodoune1g@networksolutions.com', '827-581-8299', 'Registered Nurse');
insert into customer (first_name, last_name, email, phone, job) values ('Sherri', 'Quarry', 'squarry1h@noaa.gov', '459-455-0112', 'Database Administrator I');
insert into customer (first_name, last_name, email, phone, job) values ('Ethelyn', 'Batkin', 'ebatkin1i@w3.org', '164-838-2466', 'Help Desk Operator');
insert into customer (first_name, last_name, email, phone, job) values ('Alan', 'Pitrelli', 'apitrelli1j@myspace.com', '803-539-0269', 'Electrical Engineer');
insert into customer (first_name, last_name, email, phone, job) values ('Anya', 'Jados', 'ajados1k@mapquest.com', '944-768-0829', 'Financial Advisor');
insert into customer (first_name, last_name, email, phone, job) values ('Whitaker', 'Orbell', 'worbell1l@columbia.edu', '913-427-2287', 'VP Product Management');
insert into customer (first_name, last_name, email, phone, job) values ('Augustina', 'Bourgeois', 'abourgeois1m@com.com', '161-143-8195', 'Developer I');
insert into customer (first_name, last_name, email, phone, job) values ('Portie', 'Lamshead', 'plamshead1n@tuttocitta.it', '609-442-4162', 'Financial Analyst');
insert into customer (first_name, last_name, email, phone, job) values ('Harlene', 'Lamey', 'hlamey1o@studiopress.com', '239-234-6270', 'Sales Representative');
insert into customer (first_name, last_name, email, phone, job) values ('Caresse', 'Whyborne', 'cwhyborne1p@mozilla.com', '190-355-7440', 'Analyst Programmer');
insert into customer (first_name, last_name, email, phone, job) values ('Syd', 'Aspray', 'saspray1q@ucsd.edu', '651-630-8772', 'Web Developer III');
insert into customer (first_name, last_name, email, phone, job) values ('Rafe', 'Creighton', 'rcreighton1r@sphinn.com', '456-581-9374', 'Director of Sales');
insert into customer (first_name, last_name, email, phone, job) values ('Boigie', 'Velte', 'bvelte1s@ed.gov', '971-945-7569', 'Nurse');
insert into customer (first_name, last_name, email, phone, job) values ('Artie', 'MacFaul', 'amacfaul1t@soundcloud.com', '541-971-4671', 'Teacher');
insert into customer (first_name, last_name, email, phone, job) values ('Rafaela', 'Barabisch', 'rbarabisch1u@dailymail.co.uk', '111-594-9947', 'Analog Circuit Design manager');
insert into customer (first_name, last_name, email, phone, job) values ('Hinda', 'Odegaard', 'hodegaard1v@addtoany.com', '449-756-6313', 'Environmental Specialist');
insert into customer (first_name, last_name, email, phone, job) values ('Tito', 'Kenlin', 'tkenlin1w@google.co.jp', '486-885-1493', 'Sales Associate');
insert into customer (first_name, last_name, email, phone, job) values ('Hyacinthe', 'Grinaway', 'hgrinaway1x@weebly.com', '370-736-7269', 'Accountant IV');
insert into customer (first_name, last_name, email, phone, job) values ('Sheila', 'Marzele', 'smarzele1y@pcworld.com', '159-974-5610', 'Structural Analysis Engineer');
insert into customer (first_name, last_name, email, phone, job) values ('Rosita', 'Dougary', 'rdougary1z@cmu.edu', '413-684-7534', 'Teacher');
insert into customer (first_name, last_name, email, phone, job) values ('Sela', 'Mintram', 'smintram20@google.com', '704-481-7800', 'Assistant Professor');
insert into customer (first_name, last_name, email, phone, job) values ('Ros', 'Gerrels', 'rgerrels21@hugedomains.com', '457-525-4125', 'Analog Circuit Design manager');
insert into customer (first_name, last_name, email, phone, job) values ('Francis', 'Garvill', 'fgarvill22@hatena.ne.jp', '438-792-3124', 'Nuclear Power Engineer');
insert into customer (first_name, last_name, email, phone, job) values ('Conchita', 'Comerford', 'ccomerford23@elegantthemes.com', '919-347-9422', 'Office Assistant III');
insert into customer (first_name, last_name, email, phone, job) values ('Fabe', 'Denisard', 'fdenisard24@guardian.co.uk', '232-269-9688', 'Quality Control Specialist');
insert into customer (first_name, last_name, email, phone, job) values ('Philbert', 'Laingmaid', 'plaingmaid25@i2i.jp', '250-416-5987', 'Recruiting Manager');
insert into customer (first_name, last_name, email, phone, job) values ('Caterina', 'Tuxell', 'ctuxell26@rediff.com', '343-592-8848', 'Social Worker');
insert into customer (first_name, last_name, email, phone, job) values ('Georas', 'Wilcockes', 'gwilcockes27@godaddy.com', '842-164-7319', 'Recruiting Manager');
insert into customer (first_name, last_name, email, phone, job) values ('Hebert', 'Vayne', 'hvayne28@thetimes.co.uk', '233-803-6917', 'Geologist IV');
insert into customer (first_name, last_name, email, phone, job) values ('Rhys', 'Symper', 'rsymper29@accuweather.com', '931-538-2313', 'General Manager');
insert into customer (first_name, last_name, email, phone, job) values ('Cathee', 'Glowacki', 'cglowacki2a@myspace.com', '550-895-6761', 'Business Systems Development Analyst');
insert into customer (first_name, last_name, email, phone, job) values ('Weston', 'Bastian', 'wbastian2b@elegantthemes.com', '257-257-3909', 'Executive Secretary');
insert into customer (first_name, last_name, email, phone, job) values ('Rey', 'Wooster', 'rwooster2c@mtv.com', '620-792-5490', 'Staff Accountant III');
insert into customer (first_name, last_name, email, phone, job) values ('Crissie', 'Iiannone', 'ciiannone2d@wp.com', '828-839-2917', 'Executive Secretary');
insert into customer (first_name, last_name, email, phone, job) values ('Alica', 'Dunlap', 'adunlap2e@reverbnation.com', '344-121-2002', 'Tax Accountant');
insert into customer (first_name, last_name, email, phone, job) values ('Auberta', 'Waight', 'awaight2f@hubpages.com', '725-514-0048', 'Environmental Tech');
insert into customer (first_name, last_name, email, phone, job) values ('Elianore', 'Doughtery', 'edoughtery2g@people.com.cn', '405-101-6553', 'Budget/Accounting Analyst IV');
insert into customer (first_name, last_name, email, phone, job) values ('Jayme', 'Scroxton', 'jscroxton2h@eepurl.com', '258-369-5840', 'Research Nurse');
insert into customer (first_name, last_name, email, phone, job) values ('Corly', 'Varcoe', 'cvarcoe2i@yahoo.co.jp', '270-710-1626', 'Engineer I');
insert into customer (first_name, last_name, email, phone, job) values ('Gusella', 'Fleury', 'gfleury2j@wikispaces.com', '822-530-2570', 'Associate Professor');
insert into customer (first_name, last_name, email, phone, job) values ('Addie', 'Whorf', 'awhorf2k@skype.com', '527-510-1246', 'Dental Hygienist');
insert into customer (first_name, last_name, email, phone, job) values ('Robby', 'Paviour', 'rpaviour2l@pen.io', '214-763-8592', 'Marketing Manager');
insert into customer (first_name, last_name, email, phone, job) values ('Sandi', 'Terrett', 'sterrett2m@nih.gov', '457-672-2320', 'Research Associate');
insert into customer (first_name, last_name, email, phone, job) values ('Wilhelmine', 'Riddett', 'wriddett2n@ow.ly', '439-347-5132', 'Systems Administrator II');
insert into customer (first_name, last_name, email, phone, job) values ('Antoine', 'Patzelt', 'apatzelt2o@dion.ne.jp', '343-227-5189', 'Help Desk Operator');
insert into customer (first_name, last_name, email, phone, job) values ('Jaquith', 'Spray', 'jspray2p@apache.org', '667-106-3664', 'Social Worker');
insert into customer (first_name, last_name, email, phone, job) values ('Caleb', 'Divell', 'cdivell2q@cisco.com', '711-331-7664', 'Computer Systems Analyst I');
insert into customer (first_name, last_name, email, phone, job) values ('Cornela', 'O''Connel', 'coconnel2r@bbc.co.uk', '915-212-7069', 'Research Nurse');
